EVS-2426: expose installing hardware certificate through configuration
evbox/station-simulator pull request #128
Opened 2022-02-17 14:55 UTC by Rawan-Abdelaal

2022-02-17 15:44 UTC, akoshterek requested changes

2022-02-18 09:18 UTC, osigida approved these changes

2022-02-18 09:18 UTC, osigida commented on simulator-core/src/main/java/com/evbox/everon/ocpp/simulator/station/StationStore.java
> +            keyPair = loadKeyPair(keyPairPath);
no need to define the variable outside

2022-02-18 11:11 UTC, akoshterek approved these changes

2022-02-18 11:14 UTC, merged

2022-02-18 11:14 UTC, akoshterek commented on simulator-core/src/main/java/com/evbox/everon/ocpp/simulator/station/support/CertificateUtils.java
> +            try (JcaPEMWriter pemWriter = new JcaPEMWriter(stringWriter)){
One try block should be enough
try (StringWriter stringWriter = new StringWriter(); JcaPEMWriter pemWriter = new JcaPEMWriter(stringWriter))